### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by paulobocanegra** [kenquack/KZXT#6]
One last update to our MVP List.

Your fullstack will be an e-commerce. The main feature will be CRUD on cart items. Therefore, let's move Cart to be the 4th MVP and Reviews the 5th. Worse comes to worst, for an e-commerce we can deliver an app without reviews, but not without cart items.

**Comment by kenquack** [comment]
done as well

**Comment by paulobocanegra** [comment]
Great job! 💯
