### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by paulobocanegra** [kenquack/KZXT#7]
# User Auth
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] Should look similar to real site
  - [ ] When errors are displayed, the form adjusts properly
- [ ] Smooth, bug free navigation
  - [ ] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [ ] Errors should display for both `/signup` and`/login`.
- [ ] Adequate and appropriate seeds
  - [ ] Demo Login Works

**Comment by paulobocanegra** [comment]
No Live link

**Comment by kenquack** [comment]
Added errors. I will wait a couple of days to do the changing my login button to logout if i'm logged in because on the website, it's a drop down and I don't want to have to figure that out at the moment lol
